export const data = [{
    "name": "Facebook",
    "icon": "https://res.cloudinary.com/maxworld/image/upload/v1556701094/Playstore/Facebook_icon_u6n8ls.jpg",
    "sample_image": "https://res.cloudinary.com/maxworld/image/upload/v1556711231/Playstore/placeholder-200x200_oub29j.png",
    "link": "https://www.facebook.com/",
    "description": "",
    "developers": "",
    "category": "Social",
    "rating": "4.9",
    "downloads": "86,616,849+",
    "age_required": "16+",
    "download": "download"
},
{
    "name": "Wikipedia",
    "icon": "https://res.cloudinary.com/maxworld/image/upload/v1556701659/Playstore/Wikipedia_iyj1mo.png",
    "sample_image": "https://res.cloudinary.com/maxworld/image/upload/v1556711231/Playstore/placeholder-200x200_oub29j.png",
    "link": "https://www.wikipedia.org/",   
    "description": "",
    "developers": "",
    "category": "Info",
    "rating": "4.2",
    "downloads": "3,734,257+",
    "age_required": "5+",
    "download": "download"
},
{
    "name": "Youtube",
    "icon": "https://res.cloudinary.com/maxworld/image/upload/v1556701659/Playstore/kisspng-youtube-computer-icons-logo-clip-art-classic-youtube-icon-5ab1bdde227952.3405347515215979181412_bfc3tg.png",
    "sample_image": "https://res.cloudinary.com/maxworld/image/upload/v1556711231/Playstore/placeholder-200x200_oub29j.png",
    "link": "https://www.youtube.com/",
    "description": "",
    "developers": "",
    "category": "Entertainment",
    "rating": "4.9",
    "downloads": "79,725,839+",
    "age_required": "16+",
    "download": ""
},
{
    "name": "Miniclip",
    "icon": "https://res.cloudinary.com/maxworld/image/upload/v1556701659/Playstore/miniclip_k3b8l4.png",
    "sample_image": "https://res.cloudinary.com/maxworld/image/upload/v1556711231/Playstore/placeholder-200x200_oub29j.png",
    "link": "https://www.miniclip.com/games/en/",
    "description": "",
    "developers": "",
    "category": "Games",
    "rating": "",
    "downloads": "231,704+",
    "age_required" : "6+",
    "download": ""
},
{
    "name": "Stackoverflow",
    "icon": "https://res.cloudinary.com/maxworld/image/upload/v1556901046/Playstore/stackoverflow_gsfqlu.png",
    "sample_image": "https://res.cloudinary.com/maxworld/image/upload/v1556711231/Playstore/placeholder-200x200_oub29j.png",
    "link": "https://stackoverflow.com/",
    "description": "",
    "developers": "",
    "category": "Info",
    "rating": "5,471,704+",
    "downloads": "",
    "age_required" : "10+",
    "download": ""
},
{
    "name": "Twitter",
    "icon": "https://res.cloudinary.com/maxworld/image/upload/v1556701658/Playstore/Twitter-Logo_ikuavu.png",
    "sample_image": "https://res.cloudinary.com/maxworld/image/upload/v1556711231/Playstore/placeholder-200x200_oub29j.png",
    "link": "https://www.twitter.com/",
    "description": "",
    "developers": "",
    "category": "Social",
    "rating": "",
    "downloads": "",
    "age_required" : "13+",
    "download": ""
},
{
    "name": "Netflix",
    "icon": "https://res.cloudinary.com/maxworld/image/upload/v1556702082/Playstore/netflix_nvzjag.png",
    "sample_image": "https://res.cloudinary.com/maxworld/image/upload/v1556711231/Playstore/placeholder-200x200_oub29j.png",
    "link": "https://www.netflix.com/pk/",
    "description": "",
    "developers": "",
    "category": "Entertainment",
    "rating": "",
    "downloads": "",
    "age_required" : "18+",
    "download": ""
},
{
    "name": "Gmail",
    "icon": "https://res.cloudinary.com/maxworld/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1556901039/Playstore/gmail_ocg79e.png",
    "sample_image": "https://res.cloudinary.com/maxworld/image/upload/v1556711231/Playstore/placeholder-200x200_oub29j.png",
    "link": "https://gmail.com/",
    "description": "",
    "developers": "",
    "category": "Social",
    "rating": "",
    "downloads": "",
    "age_required" : "15+",
    "download": ""
},
{
    "name": "Maps",
    "icon": "https://res.cloudinary.com/maxworld/image/upload/v1556702086/Playstore/map_y6v7ox.png",
    "sample_image": "https://res.cloudinary.com/maxworld/image/upload/v1556711231/Playstore/placeholder-200x200_oub29j.png",
    "link": "https://www.google.com/maps",
    "description": "",
    "developers": "",
    "category": "Info",
    "rating": "4.5",
    "downloads": "",
    "age_required" : "3+",
    "download": ""
},
{
    "name": "Fiverr",
    "icon": "https://res.cloudinary.com/maxworld/image/upload/v1556703089/Playstore/fiverr_dbhzkl.jpg",
    "sample_image": "https://res.cloudinary.com/maxworld/image/upload/v1556711231/Playstore/placeholder-200x200_oub29j.png",
    "link": "https://www.fiverr.com/",
    "description": "",
    "developers": "",
    "category": "Online_Earning",
    "rating": "4.8",
    "downloads": "129,269+",
    "age_required" : "18+",
    "download": ""
},
{
    "name": "Whatsapp",
    "icon": "https://res.cloudinary.com/maxworld/image/upload/v1556901039/Playstore/whatsapp_oqf9my.png",
    "sample_image": "https://res.cloudinary.com/maxworld/image/upload/v1556711231/Playstore/placeholder-200x200_oub29j.png",
    "link": "https://web.whatsapp.com/",
    "description": "",
    "developers": "",
    "category": "Social",
    "rating": "4.7",
    "downloads": "87,898,293+",
    "age_required" : "16+",
    "download": ""
},
{
    "name": "Y8",
    "icon": "https://res.cloudinary.com/maxworld/image/upload/v1556703975/Playstore/Y8_ahqhzj.jpg",
    "sample_image": "https://res.cloudinary.com/maxworld/image/upload/v1556711231/Playstore/placeholder-200x200_oub29j.png",
    "link": "https://www.y8.com/",
    "description": "",
    "developers": "",
    "category": "Games",
    "rating": "4.3",
    "downloads": "346,130+",
    "age_required" : "12+"
},
{
    "name": "Upwork",
    "icon": "https://res.cloudinary.com/maxworld/image/upload/v1556704090/Playstore/upwork_acyphs.png",
    "sample_image": "https://res.cloudinary.com/maxworld/image/upload/v1556711231/Playstore/placeholder-200x200_oub29j.png",
    "link": "https://www.upwork.com/",
    "description": "",
    "developers": "",
    "category": "Online_Earning",
    "rating": "4.4",
    "downloads": "2,568,730+",
    "age_required" : "18+"
},
{
    "name": "",
    "icon": "",
    "sample_image": "https://res.cloudinary.com/maxworld/image/upload/v1556711231/Playstore/placeholder-200x200_oub29j.png",
    "link": "",
    "description": "",
    "developers": "",
    "category": "",
    "rating": "",
    "downloads": "",
    "age_required" : ""
},
{
    "name": "",
    "icon": "",
    "sample_image": "https://res.cloudinary.com/maxworld/image/upload/v1556711231/Playstore/placeholder-200x200_oub29j.png",
    "link": "",
    "description": "",
    "developers": "",
    "category": "",
    "rating": "",
    "downloads": "",
    "age_required" : ""
}
]